apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: generation-2
  namespace: "980226732151"
  selfLink: /apis/serving.knative.dev/v1/namespaces/980226732151/services/generation-2
  uid: 9b051fcb-422f-4626-8d41-849476ae8e2f
  resourceVersion: AAX9a1OkVi4
  generation: 2
  creationTimestamp: "2023-06-06T00:40:52.700991Z"
  labels:
    goog-managed-by: cloudfunctions
    goog-cloudfunctions-runtime: nodejs18
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: console-cloud
    serving.knative.dev/creator: service-980226732151@gcf-admin-robot.iam.gserviceaccount.com
    serving.knative.dev/lastModifier: service-980226732151@gcf-admin-robot.iam.gserviceaccount.com
    cloudfunctions.googleapis.com/function-id: Generation-2
    run.googleapis.com/operation-id: d61045b6-7216-4bcc-8eb6-772b397b2119
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: generation-2-00002-maz
      annotations:
        run.googleapis.com/client-name: console-cloud
        cloudfunctions.googleapis.com/trigger-type: HTTP_TRIGGER
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 60
      serviceAccountName: 980226732151-compute@developer.gserviceaccount.com
      containers:
        - image: us-central1-docker.pkg.dev/first-project-387902/gcf-artifacts/g-generation--2:version_1
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 167m
              memory: 256Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
  traffic:
    - percent: 100
      latestRevision: true
status:
  observedGeneration: 2
  conditions:
    - type: Ready
      status: "True"
      lastTransitionTime: "2023-06-06T00:44:50.048682Z"
    - type: ConfigurationsReady
      status: "True"
      lastTransitionTime: "2023-06-06T00:44:40.418371Z"
    - type: RoutesReady
      status: "True"
      lastTransitionTime: "2023-06-06T00:44:50.160174Z"
  latestReadyRevisionName: generation-2-00002-maz
  latestCreatedRevisionName: generation-2-00002-maz
  traffic:
    - revisionName: generation-2-00002-maz
      percent: 100
      latestRevision: true
  url: https://generation-2-43fqthdw4a-uc.a.run.app
  address:
    url: https://generation-2-43fqthdw4a-uc.a.run.app
