# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubernetes.io/change-cause: Deployment UPDATE - App Version 2.0.0 - SET IMAGE
      OPTION
  creationTimestamp: "2023-07-06T12:03:10Z"
  generation: 5
  labels:
    app: my-first-deployment
  name: my-first-deployment
  namespace: default
  resourceVersion: "3605714"
  uid: 28a9fc9c-dbcf-44c1-b94b-1d1eb17fb593
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-first-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
         app: my-first-deployment
    spec:
      containers:
      - image: stacksimplify/kubenginx:3.0.0
        imagePullPolicy: IfNotPresent
        name: kubenginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2023-07-06T12:20:49Z"
    lastUpdateTime: "2023-07-06T12:20:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-07-06T12:03:10Z"
    lastUpdateTime: "2023-07-06T12:35:30Z"
    message: ReplicaSet "my-first-deployment-5bb6c98c88" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
